#!/usr/bin/env python
### Copyright (C) 2007 Peter Williams <peter_ono@users.sourceforge.net>

### This program is free software; you can redistribute it and/or modify
### it under the terms of the GNU General Public License as published by
### the Free Software Foundation; version 2 of the License only.

### This program is distributed in the hope that it will be useful,
### but WITHOUT ANY WARRANTY; without even the implied warranty of
### MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
### GNU General Public License for more details.

### You should have received a copy of the GNU General Public License
### along with this program; if not, write to the Free Software
### Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

import sys, os, getopt, setup_generic

# read required directory from the command line

def usage():
    print "Usage: create_deb_spec [dependency]*"

try:
    option_list, arg_list = getopt.getopt(sys.argv[1:], "")
except getopt.GetoptError, err:
    sys.stderr.write(str(err) + os.linesep)
    usage()
    sys.exit(1)

print 'Package: %s' % setup_generic.NAME
print 'Version: %s' % setup_generic.VERSION
print 'Maintainer: %s <%s>' % (setup_generic.AUTHOR, setup_generic.AUTHOR_EMAIL)
print 'Description: %s' % setup_generic.DESCRIPTION
first = True
for line in setup_generic.LONG_DESCRIPTION.splitlines():
    if first and not line:
        first = False
        continue
    print ' %s' % line
print 'Section: devel'
print 'Priority: optional'
print 'Architecture: all'
print 'Depends: %s' % ', '.join(arg_list)
