#!/usr/bin/env python
### Copyright (C) 2007 Peter Williams <pwil3058@bigpond.net.au>

### This program is free software; you can redistribute it and/or modify
### it under the terms of the GNU General Public License as published by
### the Free Software Foundation; version 2 of the License only.

### This program is distributed in the hope that it will be useful,
### but WITHOUT ANY WARRANTY; without even the implied warranty of
### MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
### GNU General Public License for more details.

### You should have received a copy of the GNU General Public License
### along with this program; if not, write to the Free Software
### Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

import sys, os, getopt, gtk, gwsmhg_pkg.gwsm, gwsmhg_pkg.hg_mq_ifce

# read required directory from the command line

def usage():
    print "Usage: gwsmhg [dir]"

try:
    option_list, arg_list = getopt.getopt(sys.argv[1:], "")
except getopt.GetoptError, err:
    sys.stderr.write(str(err) + os.linesep)
    usage()
    sys.exit(1)

if not len(arg_list) == 1:
    usage()
    sys.exit(1)

if len(arg_list) == 1:
    try:
        os.chdir(sys.argv[1])
    except OSError, msg:
        sys.stderr.write(str(msg) + os.linesep)
        sys.exit(2)

app = gwsmhg_pkg.gwsm.gwsm(gwsmhg_pkg.hg_mq_ifce.SCMInterface)
app.show()
gtk.main()

